from django.urls import path, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from tpv import views

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico', permanent=False)),

    # Admin Panel: Stock, Informe Semanal, Previsión Compras (ANTES del admin porcatch-all)
    path('admin/gerencia/', views.admin_gerencia_dashboard, name='admin_gerencia_dashboard'),
    path('admin/stock-dashboard/', views.admin_stock_dashboard, name='admin_stock_dashboard'),
    path('admin/informe-semanal/', views.admin_informe_semanal, name='admin_informe_semanal'),
    path('admin/prevision-compras/', views.admin_prevision_compras, name='admin_prevision_compras'),

    # Exportaciones Excel/PDF desde Admin
    path('admin/stock-dashboard/excel/', views.admin_exportar_stock_excel, name='admin_exportar_stock_excel'),
    path('admin/informe-semanal/excel/', views.admin_exportar_informe_semanal_excel, name='admin_exportar_informe_semanal_excel'),
    path('admin/informe-semanal/pdf/', views.admin_exportar_informe_semanal_pdf, name='admin_exportar_informe_semanal_pdf'),
    path('admin/prevision-compras/excel/', views.admin_exportar_prevision_excel, name='admin_exportar_prevision_excel'),
    path('admin/prevision-compras/pdf/', views.admin_exportar_prevision_pdf, name='admin_exportar_prevision_pdf'),

    path('admin/', admin.site.urls),
    path('', views.vista_terminal_pos, name='pos_home'),
    path('api/registrar-cobro/', views.api_registrar_cobro, name='api_cobro'),
    path('api/dashboard-gerencia/', views.vista_dashboard_gerencia, name='api_dashboard'),
    path('api/mesas/crear/', views.api_crear_mesa, name='api_crear_mesa'),
    path('bitacora/', views.vista_bitacora, name='bitacora'),
    path('cierre-caja/', views.vista_cierre_caja, name='cierre_caja'),
    path('api/turno/abrir/', views.api_abrir_turno, name='api_abrir_turno'),
    path('api/turno/cerrar/', views.api_cerrar_turno, name='api_cerrar_turno'),
    path('cocina/', views.vista_cocina, name='cocina'),
    path('api/cocina/actualizar/', views.api_actualizar_pedido_cocina, name='api_cocinaActualizar'),
    path('api/cocina/pedidos/', views.api_pedido_cocina, name='api_cocinaPedidos'),
    path('menu-dia/', views.vista_menu_dia, name='menu_dia'),
    path('reservas/', views.vista_reservas, name='reservas'),
    path('api/reservas/crear/', views.api_crear_reserva, name='api_crear_reserva'),
    path('api/reservas/estado/', views.api_estado_reserva, name='api_estado_reserva'),
    path('api/cupon/validar/', views.api_validar_cupon, name='api_validar_cupon'),
    path('api/buscar-productos/', views.api_buscar_productos, name='api_buscar_productos'),
    path('api/top-vendidos/', views.api_top_vendidos, name='api_top_vendidos'),
    path('pdf/ticket/<int:venta_id>/', views.pdf_ticket, name='pdf_ticket'),
    path('pdf/reporte-diario/', views.pdf_reporte_diario, name='pdf_reporte_diario'),
    path('empleados/', views.vista_empleados, name='empleados'),
    path('api/empleados/crear/', views.api_crear_empleado, name='api_crear_empleado'),
    path('api/recomendaciones/', views.api_recomendaciones, name='api_recomendaciones'),
    path('api/metas-hoy/', views.api_metas_hoy, name='api_metas_hoy'),
    path('pantalla-cliente/', views.vista_pantalla_cliente, name='pantalla_cliente'),
    path('api/estado-pedido-cliente/', views.api_estado_pedido_cliente, name='api_estado_pedido_cliente'),
    path('pdf/ticket-qr/<int:venta_id>/', views.pdf_ticket_con_qr, name='pdf_ticket_qr'),
    path('api/buscar-codigo-barras/', views.api_buscar_codigo_barras, name='api_buscar_codigo_barras'),
    path('api/split-bill/', views.api_split_bill, name='api_split_bill'),
    path('api/clientes/', views.api_clientes, name='api_clientes'),
    path('api/clientes/crear/', views.api_crear_cliente, name='api_crear_cliente'),
    path('api/transferir-mesa/', views.api_transferir_mesa, name='api_transferir_mesa'),
    path('api/timer-cocina/', views.api_timer_cocina, name='api_timer_cocina'),
    path('api/clima-sugerencias/', views.api_clima_sugerencias, name='api_clima_sugerencias'),
    path('heatmap/', views.vista_heatmap, name='heatmap'),
    path('api/forecast/', views.api_forecast, name='api_forecast'),
    path('plano/', views.vista_plano, name='plano'),
    path('api/plano/guardar/', views.api_guardar_posiciones, name='api_guardar_posiciones'),
    path('menu/<int:mesa_numero>/', views.vista_pedido_movil, name='pedido_movil'),
    path('api/pedido-movil/crear/', views.api_pedido_movil_crear, name='api_pedido_movil_crear'),
    path('api/pedido-movil/pendientes/', views.api_pedidos_movil_pendientes, name='api_pedidos_movil_pendientes'),
    path('api/social-proof/', views.api_social_proof, name='api_social_proof'),
    path('api/satisfaccion/', views.api_satisfaccion, name='api_satisfaccion'),
    path('api/stats-satisfaccion/', views.api_stats_satisfaccion, name='api_stats_satisfaccion'),
    path('api/cola/', views.api_cola_estado, name='api_cola_estado'),
    path('api/cola/accion/', views.api_cola_siguiente, name='api_cola_siguiente'),
    path('cola/', views.vista_cola, name='cola'),
    path('accounts/logout/', views.vista_logout, name='logout'),
    path('api/cola/siguiente/', views.api_cola_siguiente, name='api_cola_siguiente'),
    path('api/cola/estado/', views.api_cola_estado, name='api_cola_estado'),
    path('api/anuncio-voz/', views.api_anuncio_voz, name='api_anuncio_voz'),
    path('api/competicion/', views.api_competicion, name='api_competicion'),
    path('api/sugerencia-hora/', views.api_sugerencia_hora, name='api_sugerencia_hora'),
    path('api/stock-bajo/', views.api_stock_bajo, name='api_stock_bajo'),
    path('api/pedidos-proveedor/', views.api_generar_pedido_proveedor, name='api_pedidos_proveedor'),
    path('api/chat/mensajes/', views.api_chat_mensajes, name='api_chat_mensajes'),
    path('api/chat/enviar/', views.api_chat_enviar, name='api_chat_enviar'),
    path('escaparate/', views.vista_escaparate, name='vista_escaparate'),
    path('exportar-excel/', views.api_exportar_excel, name='api_exportar_excel'),
    path('api/producto/<int:producto_id>/animacion/', views.api_producto_animacion, name='api_producto_animacion'),
    path('api/firma/', views.api_guardar_firma, name='api_guardar_firma'),
    path('kiosk/', views.vista_kiosk, name='vista_kiosk'),
    path('api/kiosk/pedido/', views.api_kiosk_pedido, name='api_kiosk_pedido'),
    path('api/receta/<int:articulo_id>/pasos/', views.api_receta_pasos, name='api_receta_pasos'),
    path('api/receta/paso/crear/', views.api_crear_paso_receta, name='api_crear_paso_receta'),
    path('api/propina/', views.api_calcular_propina, name='api_calcular_propina'),
    path('api/heatmap/realtime/', views.api_heatmap_tiempo_real, name='api_heatmap_realtime'),
    path('tv/', views.vista_tv_display, name='vista_tv_display'),
    path('api/notificacion/crear/', views.api_crear_notificacion, name='api_crear_notificacion'),
    path('api/notificacion/pendientes/', views.api_notificaciones_pendientes, name='api_notificaciones_pendientes'),
    path('api/backup/', views.api_backup_usb, name='api_backup_usb'),
    path('api/descuentos-activos/', views.api_descuentos_activos, name='api_descuentos_activos'),
    path('api/aplicar-descuento/', views.api_aplicar_descuento, name='api_aplicar_descuento'),
    path('api/cumpleanos/', views.api_cumpleanos_hoy, name='api_cumpleanos_hoy'),
    path('api/rating/<int:articulo_id>/', views.api_rating_producto, name='api_rating_producto'),
    path('api/rating/crear/', views.api_crear_rating, name='api_crear_rating'),
    path('api/top-ratings/', views.api_top_ratings, name='api_top_ratings'),
    path('api/combos/', views.api_combos_disponibles, name='api_combos_disponibles'),
    path('api/combo/crear/', views.api_crear_combo, name='api_crear_combo'),
    path('api/mapa-mesas/', views.api_mapa_mesas, name='api_mapa_mesas'),
    path('api/cambio/', views.api_calcular_cambio, name='api_calcular_cambio'),
    path('reviews/', views.vista_reviews, name='vista_reviews'),
    path('api/reviews/', views.api_reviews, name='api_reviews'),
    path('api/reviews/crear/', views.api_crear_review, name='api_crear_review'),
    path('api/sheets-sync/', views.api_sheets_sync, name='api_sheets_sync'),
    path('accounts/', include('django.contrib.auth.urls')),
]
