# Generated by Django 6.0.7 on 2026-07-13 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('icono', models.CharField(default='☕', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InsumoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Ingrediente')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Actual')),
                ('cantidad_minima', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Minimo de Alerta')),
                ('unidad_medida', models.CharField(choices=[('g', 'Gramos'), ('ml', 'Mililitros'), ('ud', 'Unidades')], default='g', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio_sin_iva', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio Base (Sin IVA)')),
                ('tipo_iva', models.CharField(choices=[('10.00', '10% (Hosteleria / Alimentacion)'), ('21.00', '21% (Bebidas Alcoholicas / General)'), ('4.00', '4% (Superreducido)')], default='10.00', max_length=5)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='tpv.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='ComposicionReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=2, help_text='Cantidad usada por cada venta', max_digits=6)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='tpv.articulo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpv.insumomateriaprima')),
            ],
        ),
        migrations.CreateModel(
            name='OperacionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('subtotal_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_facturado', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=15)),
                ('hash_seguridad', models.CharField(blank=True, editable=False, max_length=64)),
                ('empleado_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LineaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.PositiveIntegerField(default=1)),
                ('precio_aplicado_con_iva', models.DecimalField(decimal_places=2, max_digits=6)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpv.articulo')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='tpv.operacionventa')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_gasto', models.DateTimeField(auto_now_add=True)),
                ('empleado_autoriza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
