# Generated by Django 6.0.7 on 2026-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('sillas', models.PositiveIntegerField(default=4)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
