# Generated by Django 6.0.7 on 2026-07-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0002_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacionventa',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='tpv.mesa'),
        ),
    ]
