# Generated by Django 6.0.5 on 2026-07-14 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0003_operacionventa_mesa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesion'), ('LOGOUT', 'Cierre de sesion'), ('VENTA', 'Cobro / Venta'), ('GASTO', 'Registro de gasto'), ('CREAR', 'Creacion'), ('EDITAR', 'Edicion'), ('ELIMINAR', 'Eliminacion')], max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('detalles_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-fecha'],
            },
        ),
    ]
