# Generated by Django 6.0.5 on 2026-07-14 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0004_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDelDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_promo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('franja', models.CharField(choices=[('MANANA', 'Manana (8h-12h)'), ('MEDIODIA', 'Mediodia (12h-16h)'), ('TARDE', 'Tarde (16h-20h)'), ('TODO', 'Todo el dia')], default='TODO', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_dia', to='tpv.articulo')),
            ],
            options={
                'verbose_name': 'Menu del Dia',
                'verbose_name_plural': 'Menus del Dia',
            },
        ),
        migrations.CreateModel(
            name='PedidoCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.PositiveIntegerField(default=1)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARANDO', 'En preparacion'), ('LISTO', 'Listo para servir'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_listo', models.DateTimeField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpv.articulo')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cocina', to='tpv.operacionventa')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('num_personas', models.PositiveIntegerField(default=2)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=15)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='tpv.mesa')),
            ],
            options={
                'ordering': ['fecha_reserva', 'hora_reserva'],
            },
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_teorico', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_real', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('tickets_cerrados', models.PositiveIntegerField(default=0)),
                ('cerrado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_apertura'],
            },
        ),
    ]
