# Generated by Django 6.0.5 on 2026-07-14 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0005_menudeldia_pedidococina_reserva_turnocaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuponDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('FIJO', 'Importe fijo (EUR)')], default='PORCENTAJE', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('minimo_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('usos_maximos', models.PositiveIntegerField(default=0, help_text='0 = sin limite')),
                ('usos_realizados', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='operacionventa',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='operacionventa',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tpv.cupondescuento'),
        ),
        migrations.CreateModel(
            name='PerfilEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CAJERO', 'Cajero'), ('COCINERO', 'Cocinero'), ('CAMARERO', 'Camarero'), ('GERENTE', 'Gerente')], default='CAJERO', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('pin_acceso', models.CharField(blank=True, help_text='PIN para acceso rapido', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
