# Generated by Django 6.0.5 on 2026-07-14 07:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0006_cupondescuento_operacionventa_descuento_aplicado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('objetivo_tickets', models.PositiveIntegerField(default=50)),
                ('objetivo_ingresos', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
            ],
        ),
    ]
