# Generated by Django 6.0.5 on 2026-07-14 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0007_metadiaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('nivel', models.CharField(choices=[('BRONCE', 'Bronce'), ('PLATA', 'Plata'), ('ORO', 'Oro'), ('PLATINO', 'Platino')], default='BRONCE', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Codigo de barras EAN-13', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='operacionventa',
            name='puntos_ganados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operacionventa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='tpv.cliente'),
        ),
    ]
