# Generated by Django 6.0.5 on 2026-07-14 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0008_cliente_articulo_codigo_barras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Plano Principal', max_length=100)),
                ('ancho', models.PositiveIntegerField(default=800)),
                ('alto', models.PositiveIntegerField(default=600)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='operacionventa',
            name='satisfaccion',
            field=models.CharField(blank=True, choices=[('EXCELENTE', '😍'), ('BUENA', '🙂'), ('NORMAL', '😐'), ('MALA', '😠')], help_text='Valoracion del cliente', max_length=10),
        ),
        migrations.CreateModel(
            name='ColaNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('ESPERANDO', 'Esperando'), ('LLAMANDO', 'Llamando'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado')], default='ESPERANDO', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('numero', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='PedidoMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('CONFIRMADO', 'Confirmado'), ('PREPARANDO', 'Preparando'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECIBIDO', max_length=12)),
                ('cliente_nombre', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_movil', to='tpv.mesa')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedidoMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.PositiveIntegerField(default=1)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tpv.articulo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='tpv.pedidomovil')),
            ],
        ),
        migrations.CreateModel(
            name='MesaPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField(default=100)),
                ('y', models.PositiveIntegerField(default=100)),
                ('color', models.CharField(default='#00d4ff', max_length=7)),
                ('mesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posicion', to='tpv.mesa')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_pos', to='tpv.planorestaurante')),
            ],
        ),
    ]
