# Generated by Django 6.0.5 on 2026-07-14 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0010_mensajechat_pedidoproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('url', models.CharField(blank=True, max_length=300)),
                ('enviada', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirmaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_firma', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to='tpv.operacionventa')),
            ],
        ),
        migrations.CreateModel(
            name='PasoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tiempo_minutos', models.PositiveIntegerField(default=0)),
                ('consejo', models.TextField(blank=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='tpv.articulo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
