# Generated by Django 6.0.7 on 2026-07-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpv', '0012_combo_reviewrestaurante_comboitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('destinatarios', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('enviado', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Email',
                'verbose_name_plural': 'Logs de Emails',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='email_proveedor',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Proveedor'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del Cliente'),
        ),
    ]
